name: Autopkg run

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 90 # Keeps your builds from running too long
    env:
      REPO_DIR: "/Users/Shared/munki_repo"
    steps:
    - name: Checkout GitHub actions 
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        #pip3 install -r requirements.txt

    - name: Install Munki
      run: |
        curl -L $(curl https://api.github.com/repos/munki/munki/releases | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["assets"][0]["browser_download_url"]') --output /tmp/munkitools.pkg
        sudo installer -verboseR -pkg /tmp/munkitools.pkg -target /

    - name: Configure Munki
      run: |
        sudo /usr/bin/defaults write com.googlecode.munki.munkiimport repo_path "${{ env.REPO_DIR }}"
        sudo /usr/bin/defaults write com.googlecode.munki.munkiimport pkginfo_extension .plist
        sudo /usr/bin/defaults write com.googlecode.munki.munkiimport default_catalog testing
      
    - name: Set up a local Munki repo
      run: |
        ## Build a local repository
        /bin/mkdir -p "${{ env.REPO_DIR }}/catalogs"
        /bin/mkdir -p "${{ env.REPO_DIR }}/manifests"
        /bin/mkdir -p "${{ env.REPO_DIR }}/pkgs"
        /bin/mkdir -p "${{ env.REPO_DIR }}/pkgsinfo"
        /bin/mkdir -p "${{ env.REPO_DIR }}/icons"
        /bin/chmod -R a+rX "${{ env.REPO_DIR }}"

    - name: Install AutoPkg
      run: |
        curl -L $(curl https://api.github.com/repos/autopkg/autopkg/releases | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["assets"][0]["browser_download_url"]') --output /tmp/autopkg.pkg
        sudo installer -verboseR -pkg /tmp/autopkg.pkg -target /

    - name: Lint recipes
      run: |
        plutil -lint **/*.recipe

    - name: Configure AutoPkg
      run: |
        sudo /usr/bin/defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$(pwd)"/overrides/
        sudo /usr/bin/defaults write com.github.autopkg RECIPE_REPO_DIR "$(pwd)"/repos/
        sudo /usr/bin/defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        sudo /usr/bin/defaults write com.github.autopkg MUNKI_REPO "${{ env.REPO_DIR }}"

    - name: Add AutoPkg repo
      run: |
        autopkg repo-add $(git config --get remote.origin.url)

    - name: Run AutoPkg
      run: $(pwd)/autopkg.sh
      shell: bash
      
    - name: Run makecatalogs and iconimporter
      run: |
        /usr/local/munki/makecatalogs ${{ env.REPO_DIR }}
        /usr/local/munki/iconimporter ${{ env.REPO_DIR }}
